[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
rust-version = "1.88"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["dotorix <dev@dtx.simplelogin.com>"]
repository = "https://github.com/sedctl/sedctl"
