[package]
name = "sedctl_api"
version = "0.0.0"
description = "[WORK IN PROGRESS | NOT USABLE YET] The api library for the sedctl project"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
