[package]
name = "sedctl_backends"
version = "0.0.0"
description = "[WIP] The TCG Storage Interface Interaction (SIIS) implementation for sedctl_tcg_storage crate"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
