[package]
name = "sedctl_tcg_storage"
version = "0.0.0"
description = "[WIP] Unofficial TCG Storage implementation for sedctl project"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
