[package]
name = "sedctl"
version = "0.0.0"
description = "[WIP] Library and CLI tool to interface with TCG Storage capable drives"
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
